INSERT INTO EMPLOYEE (EMP_ID , EMP_NAME , DEPARTMENT) VALUES (2, 'SAM'  , 'HR');
INSERT INTO EMPLOYEE (EMP_ID , EMP_NAME , DEPARTMENT) VALUES (3, 'SAMMER'  , 'TECH');
INSERT INTO EMPLOYEE (EMP_ID , EMP_NAME , DEPARTMENT) VALUES (4, 'AMY'  , 'IT');
INSERT INTO EMPLOYEE (EMP_ID , EMP_NAME , DEPARTMENT) VALUES (5, 'AMIT'  , 'QA');
INSERT INTO EMPLOYEE (EMP_ID , EMP_NAME , DEPARTMENT) VALUES (6, 'SAMMY'  , 'SALES' );